
"use client"
import "./globals.css";
import "./general-sans.css";
import Navbar from "@/components/en/navbar/Navbar";
import Footer from "@/components/en/footer/Footer";
import { usePathname } from "next/navigation";
import Whatsapp from "@/components/whatsapp/Whatsapp";

// export const metadata = {
//   title: "FGC-Website",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const url = pathname.split("/")[1];


  return (
    <html lang="en">
      <body>
        <div className="">
          {url !== "ar" && <Navbar />}
          {children}
          {url !== "ar" && <Footer />}
          <Whatsapp/>
        </div>
      </body>
    </html>
  );
}
